tap "auth0/auth0-cli"
tap "azure/functions"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "puma/puma"

brew "awscli"
brew "azure-cli"
brew "ffmpeg"
brew "graphviz"
brew "libpq"
brew "openjdk"
brew "postgresql@11"
brew "puma/puma/puma-dev"
brew "auth0/auth0-cli/auth0"
brew "azure/functions/azure-functions-core-tools@4"

cask "around"
cask "mediainfo"
cask "mkvtoolnix"
cask "ngrok"
cask "vlc"
cask "zoom"
